// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Services.djinni

#import "TXSKeyValueRepository.h"
#import <Foundation/Foundation.h>


@interface TXSConfiguration : NSObject

- (nonnull TXSKeyValueRepository *)keyValueRepository;

@end
