// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Services.djinni

#include "configuration.hpp"
#include "/Users/user/Documents/development/projects/3rdparty/djinni/example/include/nn/nn.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSConfiguration;

namespace djinni_generated {

class Configuration
{
public:
    using CppType = dropbox::oxygen::nn_shared_ptr<::textsort::Configuration>;
    using CppOptType = std::shared_ptr<::textsort::Configuration>;
    using ObjcType = TXSConfiguration*;

    using Boxed = Configuration;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

