// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from KeyValueRepository.djinni

#include "key_value_repository.hpp"
#include "/Users/user/Documents/development/projects/3rdparty/djinni/example/include/nn/nn.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSKeyValueRepository;

namespace djinni_generated {

class KeyValueRepository
{
public:
    using CppType = dropbox::oxygen::nn_shared_ptr<::textsort::KeyValueRepository>;
    using CppOptType = std::shared_ptr<::textsort::KeyValueRepository>;
    using ObjcType = TXSKeyValueRepository*;

    using Boxed = KeyValueRepository;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

