// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from KeyValueRepository.djinni

#import <Foundation/Foundation.h>


@interface TXSKeyValueRepository : NSObject

- (nonnull NSData *)getValue:(nonnull NSString *)key;

- (BOOL)setValue:(nonnull NSString *)key
           value:(nonnull NSData *)value;

- (BOOL)removeValue:(nonnull NSString *)key;

@end
