// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Services.djinni

#pragma once

#include "key_value_repository.hpp"
#include <memory>

namespace textsort {

class Configuration {
public:
    virtual ~Configuration() {}

    virtual std::shared_ptr<::textsort::KeyValueRepository> key_value_repository() = 0;
};

}  // namespace textsort
