// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from KeyValueRepository.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace textsort {

class KeyValueRepository {
public:
    virtual ~KeyValueRepository() {}

    virtual std::vector<uint8_t> get_value(const std::string & key) = 0;

    virtual bool set_value(const std::string & key, const std::vector<uint8_t> & value) = 0;

    virtual bool remove_value(const std::string & key) = 0;
};

}  // namespace textsort
